site_name: Kemux
theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - python
  logo: assets/images/logo.svg
  favicon: assets/images/favicon.ico
plugins:
  - mkdocstrings
nav:
  - Home: index.md
  - Introduction: introduction.md
  - User Guide:
    - Defining streams: user-guide/streams.md
    - Managing streams: user-guide/manager.md
    - Deploying as a service: user-guide/docker.md
  - Code Reference:
    - Manager: reference/manager.md
    - Stream: reference/stream.md
    - Schema: reference/schema.md
    - Processor: reference/processor.md
    - Additional logic: reference/logic.md
