name: Build ReadTheDocs documentation
on: [push, release]

jobs:
  docs:
    name: Trigger build from repo via API
    runs-on: ubuntu-latest
    steps:
      - name: Trigger RTDs build
        uses: dfm/rtds-action@v1
        with:
          webhook_url: ${{ secrets.RTD_URL }}
          webhook_token: ${{ secrets.RTD_TOKEN }}
          commit_ref: ${{ github.ref }}
