name: Integration tests using Dockerized services
run-name: Integration tests
on: [push]
concurrency:
  group: ${{ github.ref }}-it
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      KEMUX_IP_SUBNET: 10.5.0
      KEMUX_KAFKA_PORT: 9092
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build producer image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Producer.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: kemux/producer:latest
          build-args:
            KEMUX_KAFKA_ADDRESS=${{ env.KEMUX_IP_SUBNET }}.2:${{ env.KEMUX_KAFKA_PORT }}
      - name: Build splitter image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Splitter.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: kemux/splitter:latest
          build-args:
            KEMUX_KAFKA_ADDRESS=${{ env.KEMUX_IP_SUBNET }}.2:${{ env.KEMUX_KAFKA_PORT }}
      - name: Setup tests environment 
        uses: isbang/compose-action@v1.5.0
        env:
          KEMUX_IP_SUBNET: ${{ env.KEMUX_IP_SUBNET }}
          KEMUX_KAFKA_IP: ${{ env.KEMUX_IP_SUBNET }}.2
          KEMUX_KAFKA_PORT: ${{ env.KEMUX_KAFKA_PORT }}
          KEMUX_PRODUCER_IP: ${{ env.KEMUX_IP_SUBNET }}.3
          KEMUX_SPLITTER_IP: ${{ env.KEMUX_IP_SUBNET }}.4
        with:
          compose-file: |
            ./tests/environment/docker-compose.yml
      - name: Check connection to Kafka container
        run: |
          docker ps
