name: Integration tests using Dockerized services
run-name: Integration tests
on: [push]
concurrency:
  group: ${{ github.ref }}-it
  cancel-in-progress: true

jobs:
  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Docker swarm
        uses: isbang/compose-action@v1.5.0
        with:
          compose-file: |
            ./tests/environment/docker-compose.yml
      - name: Check connection to Kafka container
        run: |
          docker log environment-kemux-producer
