name: Integration tests using Dockerized services
run-name: Integration tests
on: [push]
concurrency:
  group: ${{ github.ref }}-it
  cancel-in-progress: true

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build producer image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Producer.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build splitter image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Splitter.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
  # integration-tests:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Setup tests environment 
  #       uses: isbang/compose-action@v1.5.0
  #       with:
  #         compose-file: |
  #           ./tests/environment/docker-compose.yml
  #     - name: Check connection to Kafka container
  #       run: |
  #         docker ps
  #         docker logs environment-kemux-producer
