name: Integration tests using Dockerized services
run-name: Integration tests
on: [push]
concurrency:
  group: ${{ github.ref }}-it
  cancel-in-progress: true

env:
  KEMUX_IP_SUBNET: 10.5.0
  KEMUX_KAFKA_PORT: 9092

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
      - name: Build producer image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Producer.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/producer.tar
          tags: kemux/producer:latest
          build-args:
            KEMUX_KAFKA_ADDRESS=${{ env.KEMUX_IP_SUBNET }}.2:${{ env.KEMUX_KAFKA_PORT }}
      - name: Build splitter image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Splitter.Dockerfile
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/splitter.tar
          tags: kemux/splitter:latest
          build-args:
            KEMUX_KAFKA_ADDRESS=${{ env.KEMUX_IP_SUBNET }}.2:${{ env.KEMUX_KAFKA_PORT }}
      - name: Upload producerimage as artifact
        uses: actions/upload-artifact@v3
        with:
          name: producer-image
          path: /tmp/producer.tar
      - name: Upload splitter image as artifact
        uses: actions/upload-artifact@v3
        with:
          name: splitter-image
          path: /tmp/splitter.tar
  integration-tests-with-kafka:
    runs-on: ubuntu-latest
    needs: build-docker-images
    steps:
      - uses: actions/checkout@v2
      - name: Download producer image
        uses: actions/download-artifact@v2
        with:
          name: producer-image
          path: /tmp/producer.tar
      - name: Download splitter image
        uses: actions/download-artifact@v2
        with:
          name: splitter-image
          path: /tmp/splitter.tar
      - name: Load built images into Docker daemon
        run: |
          docker load -i /tmp/producer.tar
          docker load -i /tmp/splitter.tar
      - name: Show loaded images
        run: |
          docker images
      - name: Setup tests environment 
        uses: isbang/compose-action@v1.5.0
        env:
          KEMUX_IP_SUBNET: ${{ env.KEMUX_IP_SUBNET }}
          KEMUX_KAFKA_IP: ${{ env.KEMUX_IP_SUBNET }}.2
          KEMUX_KAFKA_PORT: ${{ env.KEMUX_KAFKA_PORT }}
          KEMUX_PRODUCER_IP: ${{ env.KEMUX_IP_SUBNET }}.3
          KEMUX_SPLITTER_IP: ${{ env.KEMUX_IP_SUBNET }}.4
        with:
          compose-file: |
            ./tests/environment/docker-compose.yml
      - name: Check connection to Kafka container
        run: |
          docker ps
