name: Integration tests using Dockerized services
run-name: Integration tests
on: [push]
concurrency:
  group: ${{ github.ref }}-it
  cancel-in-progress: true

env:
  KEMUX_IP_SUBNET: 10.5.0
  KEMUX_KAFKA_PORT: 9092

jobs:
  build-docker-images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Lookup cache for producer image
        id: producer-cache
        uses: actions/cache@v3
        with:
          path: /tmp/producer
          key: ${{runner.os}}-producer-image
          lookup-only: true
      - name: Restore producer image from cache
        uses: actions/cache/restore@v3
        if: steps.producer-cache.outputs.cache-hit == 'true'
        with:
          path: /tmp/producer
          key: ${{runner.os}}-producer-image
      - name: Build producer image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Producer.Dockerfile
          cache-from: type=local,src=/tmp/producer
          outputs: type=local,dest=/tmp/producer
          tags: kemux/producer:latest

      - name: Lookup cache for splitter image
        id: splitter-cache
        uses: actions/cache@v3
        with:
          path: /tmp/splitter.tar
          key: ${{runner.os}}-splitter-image
          lookup-only: true
      - name: Restore splitter image from cache
        uses: actions/cache/restore@v3
        if: steps.splitter-cache.outputs.cache-hit == 'true'
        with:
          path: /tmp/splitter.tar
          key: ${{runner.os}}-splitter-image
      - name: Build splitter image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./tests/environment/docker/Splitter.Dockerfile
          cache-from: type=local,src=/tmp/splitter
          outputs: type=local,dest=/tmp/splitter
          tags: kemux/splitter:latest

      - name: Save producer image to cache
        uses: actions/cache@v3
        with:
          path: /tmp/producer
          key: ${{runner.os}}-producer-image
      - name: Save splitter image to cache
        uses: actions/cache@v3
        with:
          path: /tmp/splitter
          key: ${{runner.os}}-splitter-image

      - name: Load producer image
        run: |
          tar -cvf /tmp/producer.tar /tmp/producer
          docker load -i /tmp/producer.tar
      - name: Load splitter image
        run: |
          tar -cvf /tmp/splitter.tar /tmp/splitter
          docker load -i /tmp/splitter
      
      - name: Setup tests environment 
        uses: isbang/compose-action@v1.5.0
        env:
          KEMUX_IP_SUBNET: ${{ env.KEMUX_IP_SUBNET }}
          KEMUX_KAFKA_IP: ${{ env.KEMUX_IP_SUBNET }}.3
          KEMUX_KAFKA_PORT: ${{ env.KEMUX_KAFKA_PORT }}
          KEMUX_PRODUCER_IP: ${{ env.KEMUX_IP_SUBNET }}.4
          KEMUX_SPLITTER_IP: ${{ env.KEMUX_IP_SUBNET }}.5
        with:
          compose-file: |
            ./tests/environment/docker-compose.yml
      - name: Check connection to Kafka container
        run: |
          docker ps
